// Banco de respuestas de la máquina rival, por CATEGORÍA y LETRA.
// Revisado a mano: sólo nombres reales y conocidos. Si para una letra no existe una respuesta
// real y conocida (ej. ningún país sede del Mundial empieza con L), la lista queda vacía y la
// máquina no responde esa categoría. El test ai-answer-bank.spec.ts verifica que cada respuesta
// empiece con su letra (con las mismas reglas que se usan para los jugadores) y que no falte
// ninguna combinación de categoría y letra.
//
// Las respuestas de la máquina pasan por la misma validación con IA que las del jugador.

type Bank = Record<string, Record<string, string[]>>;

const JUGADOR_ARGENTINO: Record<string, string[]> = {
  A: ['Agüero', 'Aimar', 'Ayala'],
  B: ['Batistuta', 'Burruchaga', 'Banega'],
  C: ['Crespo', 'Cambiasso', 'Caniggia'],
  D: ['Di María', 'De Paul', 'Dybala'],
  E: ['Enzo Fernández', 'Emiliano Martínez'],
  F: ['Fillol', 'Franco Armani'],
  L: ['Lautaro Martínez', 'Lavezzi', 'Lo Celso'],
  M: ['Messi', 'Maradona', 'Mascherano'],
  N: ['Nahuel Molina', 'Nicolás Otamendi'],
  O: ['Otamendi', 'Ortega', 'Ocampos'],
  P: ['Palermo', 'Paredes', 'Passarella'],
  R: ['Riquelme', 'Redondo', 'Rodrigo De Paul'],
  S: ['Saviola', 'Simeone', 'Sorín'],
  T: ['Tevez', 'Tagliafico'],
  V: ['Verón', 'Valdano'],
};

const SELECCION_CAMPEONA: Record<string, string[]> = {
  A: ['Argentina', 'Alemania'],
  B: ['Brasil'],
  C: [],
  D: [],
  E: ['España'],
  F: ['Francia'],
  L: [],
  M: [],
  N: [],
  O: [],
  P: [],
  R: [],
  S: [],
  T: [],
  V: [],
};

export const AI_ANSWER_BANK: Bank = {
  Jugador: {
    A: ['Agüero', 'Aimar', 'Alisson'],
    B: ['Batistuta', 'Benzema', 'Busquets'],
    C: ['Cristiano Ronaldo', 'Cafú', 'Casillas'],
    D: ['Di María', 'Drogba', 'De Bruyne'],
    E: ["Eto'o", 'Ederson', 'Enzo Fernández'],
    F: ['Figo', 'Falcao', 'Forlán'],
    L: ['Lewandowski', 'Lampard', 'Lautaro Martínez'],
    M: ['Messi', 'Modric', 'Mbappé'],
    N: ['Neymar', 'Nesta', 'Neuer'],
    O: ['Oblak', 'Ochoa', 'Owen'],
    P: ['Pelé', 'Pirlo', 'Puyol'],
    R: ['Ronaldinho', 'Riquelme', 'Ramos'],
    S: ['Suárez', 'Salah', 'Scholes'],
    T: ['Totti', 'Tevez', 'Thuram'],
    V: ['Vinícius Júnior', 'Van Dijk', 'Valderrama'],
  },
  Equipo: {
    A: ['Ajax', 'Arsenal', 'Atlético de Madrid'],
    B: ['Barcelona', 'Bayern Múnich', 'Boca Juniors'],
    C: ['Chelsea', 'Celtic', 'Corinthians'],
    D: ['Deportivo La Coruña', 'Dortmund'],
    E: ['Everton', 'Estudiantes de La Plata'],
    F: ['Flamengo', 'Fiorentina', 'Fenerbahçe'],
    L: ['Liverpool', 'Lazio', 'Lanús'],
    M: ['Manchester United', 'Milan', 'Málaga'],
    N: ['Napoli', 'Newcastle', "Newell's Old Boys"],
    O: ['Olympique de Marsella', 'Olimpia'],
    P: ['Peñarol', 'Porto', 'Paris Saint-Germain'],
    R: ['Real Madrid', 'River Plate', 'Roma'],
    S: ['Sevilla', 'Santos', 'Sporting de Lisboa'],
    T: ['Tottenham', 'Talleres'],
    V: ['Valencia', 'Vélez Sarsfield', 'Villarreal'],
  },
  DT: {
    A: ['Ancelotti', 'Arteta', 'Allegri'],
    B: ['Bielsa', 'Bilardo', 'Benítez'],
    C: ['Capello', 'Conte', 'Cruyff'],
    D: ['Del Bosque', 'Deschamps'],
    E: ['Emery', 'Eriksson'],
    F: ['Ferguson', 'Flick'],
    L: ['Löw', 'Lippi', 'Luis Enrique'],
    M: ['Mourinho', 'Menotti', 'Mancini'],
    N: ['Nagelsmann'],
    O: ['Osorio'],
    P: ['Pochettino', 'Pellegrini', 'Pekerman'],
    R: ['Ranieri', 'Rijkaard', 'Ramón Díaz'],
    S: ['Scaloni', 'Simeone', 'Sabella'],
    T: ['Tuchel', 'Tite', 'Trapattoni'],
    V: ['Van Gaal', 'Valverde', 'Vicente del Bosque'],
  },
  Selección: {
    A: ['Argentina', 'Alemania', 'Australia'],
    B: ['Brasil', 'Bélgica', 'Bolivia'],
    C: ['Colombia', 'Chile', 'Croacia'],
    D: ['Dinamarca'],
    E: ['España', 'Ecuador', 'Escocia'],
    F: ['Francia', 'Finlandia'],
    L: ['Luxemburgo'],
    M: ['México', 'Marruecos'],
    N: ['Nigeria', 'Noruega', 'Nueva Zelanda'],
    O: ['Omán'],
    P: ['Paraguay', 'Perú', 'Portugal'],
    R: ['Rumania', 'Rusia'],
    S: ['Suecia', 'Suiza', 'Senegal'],
    T: ['Túnez', 'Turquía'],
    V: ['Venezuela'],
  },
  'Campeón Champions': {
    A: ['Ajax', 'Aston Villa'],
    B: ['Barcelona', 'Bayern Múnich', 'Benfica'],
    C: ['Chelsea', 'Celtic'],
    D: ['Dortmund'],
    E: ['Estrella Roja'],
    F: ['Feyenoord'],
    L: ['Liverpool'],
    M: ['Milan', 'Manchester United', 'Manchester City'],
    N: ['Nottingham Forest'],
    O: ['Olympique de Marsella'],
    P: ['Porto', 'PSV', 'Paris Saint-Germain'],
    R: ['Real Madrid'],
    S: ['Steaua Bucarest'],
    T: [],
    V: [],
  },
  'Campeón Mundial': SELECCION_CAMPEONA,
  'Jugador Argentino': JUGADOR_ARGENTINO,
  'Jugador Arg': JUGADOR_ARGENTINO,
  'Equipo Arg': {
    A: ['Argentinos Juniors', 'Arsenal de Sarandí', 'Atlético Tucumán'],
    B: ['Boca Juniors', 'Banfield', 'Belgrano'],
    C: ['Colón', 'Central Córdoba'],
    D: ['Defensa y Justicia'],
    E: ['Estudiantes de La Plata'],
    F: ['Ferro Carril Oeste'],
    L: ['Lanús'],
    M: [],
    N: ["Newell's Old Boys"],
    O: ['Olimpo'],
    P: ['Platense'],
    R: ['River Plate', 'Racing Club', 'Rosario Central'],
    S: ['San Lorenzo', 'Sarmiento'],
    T: ['Talleres', 'Tigre'],
    V: ['Vélez Sarsfield'],
  },
  'DT Arg': {
    A: ['Alfio Basile', 'Almeyda'],
    B: ['Bielsa', 'Bilardo', 'Basile'],
    C: ['Coudet'],
    D: ['Demichelis'],
    E: ['Eduardo Coudet'],
    F: [],
    L: [],
    M: ['Menotti', 'Marcelo Gallardo', 'Martino'],
    N: [],
    O: [],
    P: ['Pochettino', 'Pekerman', 'Pellegrini'],
    R: ['Ramón Díaz', 'Russo'],
    S: ['Scaloni', 'Simeone', 'Sabella'],
    T: ['Tata Martino'],
    V: ['La Volpe'],
  },
  Estadio: {
    A: ['Allianz Arena', 'Anfield'],
    B: ['Bombonera', 'Beira-Rio'],
    C: ['Camp Nou', 'Centenario'],
    D: ['Defensores del Chaco'],
    E: ['Emirates', 'Etihad'],
    F: [],
    L: ['Luzhniki', 'Libertadores de América'],
    M: ['Maracaná', 'Monumental', 'Mestalla'],
    N: ['Nuevo Gasómetro'],
    O: ['Old Trafford', 'Olímpico de Roma'],
    P: ['Parque de los Príncipes'],
    R: [],
    S: ['San Siro', 'Santiago Bernabéu', 'Signal Iduna Park'],
    T: [],
    V: ['Vicente Calderón', 'Villa Park'],
  },
  'Apodo Club': {
    A: ['Academia'],
    B: ['Blaugrana', 'Bianconeri'],
    C: ['Canallas', 'Cuervos', 'Colchoneros'],
    D: ['Diablos Rojos'],
    E: [],
    F: ['Funebreros'],
    L: ['Leprosos'],
    M: ['Millonarios', 'Merengues'],
    N: ['Nerazzurri'],
    O: [],
    P: ['Pincharratas'],
    R: ['Rojo'],
    S: ['Sabaleros'],
    T: ['Tatengues', 'Triperos'],
    V: ['Verdolagas'],
  },
  'Jugador Histórico': {
    A: ['Alfredo Di Stéfano'],
    B: ['Beckenbauer', 'Baggio', 'Bobby Charlton'],
    C: ['Cruyff', 'Cafú', 'Cantona'],
    D: ['Di Stéfano', 'Del Piero'],
    E: ['Eusébio'],
    F: ['Figo', 'Francescoli', 'Fillol'],
    L: ['Lineker'],
    M: ['Maradona', 'Maldini', 'Matthäus'],
    N: ['Nedvěd'],
    O: ['Owen'],
    P: ['Pelé', 'Platini', 'Puskás'],
    R: ['Ronaldo Nazário', 'Ronaldinho', 'Riquelme'],
    S: ['Sócrates'],
    T: ['Totti', 'Thierry Henry'],
    V: ['Van Basten', 'Valderrama'],
  },
  Clásico: {
    A: ['Clásico de Avellaneda'],
    B: [],
    C: [],
    D: [],
    E: [],
    F: [],
    L: ['Derbi de Londres'],
    M: ['Derbi madrileño', 'Derbi de Milán'],
    N: [],
    O: ['Old Firm'],
    P: ['Clásico platense'],
    R: ['Clásico rosarino'],
    S: ['Superclásico', 'Derbi sevillano'],
    T: ['Derbi de Turín'],
    V: [],
  },
  Goleador: {
    A: ['Agüero', 'Aubameyang'],
    B: ['Batistuta', 'Benzema'],
    C: ['Cristiano Ronaldo', 'Cavani'],
    D: ['Drogba', 'Dzeko'],
    E: ["Eto'o", 'Eusébio'],
    F: ['Falcao', 'Forlán'],
    L: ['Lewandowski', 'Lautaro Martínez'],
    M: ['Messi', 'Mbappé', 'Müller'],
    N: ['Neymar'],
    O: ['Owen'],
    P: ['Pelé', 'Palermo'],
    R: ['Ronaldo', 'Romário', 'Rooney'],
    S: ['Suárez', 'Shearer', 'Salah'],
    T: ['Torres', 'Thierry Henry'],
    V: ['Van Basten', 'Vieri', 'Van Nistelrooy'],
  },
  'País Sede': {
    A: ['Alemania', 'Argentina'],
    B: ['Brasil'],
    C: ['Chile', 'Corea del Sur', 'Catar', 'Canadá'],
    D: [],
    E: ['España', 'Estados Unidos'],
    F: ['Francia'],
    L: [],
    M: ['México'],
    N: [],
    O: [],
    P: [],
    R: ['Rusia'],
    S: ['Suecia', 'Suiza', 'Sudáfrica'],
    T: [],
    V: [],
  },
  'Selección Campeona': SELECCION_CAMPEONA,
  'Equipo Campeón': {
    A: ['Ajax', 'Argentinos Juniors', 'Atlético Nacional'],
    B: ['Boca Juniors', 'Barcelona', 'Bayern Múnich'],
    C: ['Colo-Colo', 'Corinthians', 'Chelsea'],
    D: ['Dortmund'],
    E: ['Estudiantes de La Plata', 'Estrella Roja'],
    F: ['Flamengo', 'Fluminense', 'Feyenoord'],
    L: ['Liverpool', 'Liga de Quito'],
    M: ['Milan', 'Manchester United'],
    N: ['Nacional', 'Nottingham Forest'],
    O: ['Olimpia', 'Once Caldas'],
    P: ['Peñarol', 'Palmeiras', 'Porto'],
    R: ['River Plate', 'Racing Club', 'Real Madrid'],
    S: ['Santos', 'São Paulo', 'San Lorenzo'],
    T: [],
    V: ['Vélez Sarsfield', 'Vasco da Gama'],
  },
  // Ojo: es la categoría que más rápido envejece (jugadores de 23 años o menos). Revisar cada temporada.
  'Jugador Promesa': {
    A: ['Arda Güler', 'Alejandro Garnacho'],
    B: [],
    C: ['Claudio Echeverri'],
    D: ['Désiré Doué'],
    E: ['Endrick', 'Estêvão'],
    F: ['Franco Mastantuono'],
    L: ['Lamine Yamal'],
    M: ['Mastantuono', 'Mainoo'],
    N: ['Nico Paz', 'Nwaneri'],
    O: [],
    P: ['Pau Cubarsí'],
    R: ['Rico Lewis'],
    S: ['Savinho'],
    T: [],
    V: ['Valentín Carboni'],
  },
};
